In [ ]:
# 1.0 References
    # Open CV
    # https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5941086
    # https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5163302
    # https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5163304
    # https://docs.scipy.org/doc/numpy/user/quickstart.html
    # https://medium.com/ibm-data-science-experience/markdown-for-jupyter-notebooks-cheatsheet-386c05aeebed
    # https://www.geeksforgeeks.org/python-remove-part-of-an-image/
    # https://realpython.com/image-processing-with-the-python-pillow-library/
    # https://pyimagesearch.com/2021/01/19/opencv-bitwise-and-or-xor-and-not/
    # https://stackoverflow.com/questions/56778752/convert-to-rgb-returns-a-rgba-image
    # https://stackoverflow.com/questions/12270163/python-pil-how-do-i-convert-1-bit-deep-images-to-rgba
    # https://stackoverflow.com/questions/47941077/saving-rgba-image-with-pil-image-frombuffer
    # https://stackoverflow.com/questions/25537137/32-bit-rgba-numpy-array-from-pil-image
    # https://stackoverflow.com/questions/57736832/how-can-you-read-rgba-using-opencv
    # https://stackoverflow.com/questions/33713199/map-an-array-to-each-item-in-another-array-python
    # https://www.geeksforgeeks.org/map-elements-of-an-array-to-elements-of-another-array/
    # https://stackoverflow.com/questions/76988988/what-is-the-pythonic-way-to-add-an-array-of-dimensions-y-x-to-the-bottom-an-ar
    # https://stackoverflow.com/questions/7372316/how-to-make-a-2d-numpy-array-a-3d-array

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from numpy import zeros, newaxis

In [2]:
sample = np.random.randint(5, size=(3, 6,4))
sample

array([[[3, 2, 0, 0],
        [1, 3, 1, 4],
        [0, 4, 0, 1],
        [3, 1, 2, 1],
        [4, 2, 3, 0],
        [3, 2, 2, 1]],

       [[3, 3, 4, 2],
        [0, 1, 0, 1],
        [1, 3, 0, 1],
        [2, 0, 1, 3],
        [4, 3, 1, 4],
        [1, 2, 0, 4]],

       [[3, 4, 1, 1],
        [3, 2, 4, 4],
        [0, 4, 3, 1],
        [4, 0, 3, 0],
        [4, 2, 0, 1],
        [3, 2, 0, 1]]])

In [3]:
type(sample)

numpy.ndarray

In [4]:
sample.shape

(3, 6, 4)

In [5]:
# extract
extract = np.zeros((1,6,4), dtype=int)
extract

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [6]:
# extract is a map of where the 4s are
for i in range(sample.shape[0]): #dimension
    for j in range(sample.shape[1]): # row
        for k in range(sample.shape[2]): #column
            if sample[i,j,k] ==4:
                extract[0,j,k] = 4 # only looking for 4s
            else:      
                pass

extract

array([[[0, 4, 4, 0],
        [0, 0, 4, 4],
        [0, 4, 0, 0],
        [4, 0, 0, 0],
        [4, 0, 0, 4],
        [0, 0, 0, 4]]])

In [7]:
type(extract)

numpy.ndarray

In [9]:
extract.shape

(1, 6, 4)

In [ ]:
# make a new 3,5,5 array in which each cell in each layer is
# either the same as 'sample', or set to 0 if its mate in 'extract' = 4
# https://stackoverflow.com/questions/33713199/map-an-array-to-each-item-in-another-array-python

In [ ]:
# iterate layer (layer = x) loop by index not 'cell', use shape to set range
    # iterate cells in layer
    # cell for cell in sample(layer x) if

# result = empty/zero/'5's array(3,5,5)

# for i in range(no. of dimensions - 1):
#    for j in range(x-coord - 1):
#        for k in range(y-coord - 1):
#            if sample(i,j,k) = extract (j,k):
#                then result(i,j,k) = 0
#            else:      
#                then result(i,j,k) = sample(i,j,k)

In [ ]:
#  think the RGBA model would be a 4D array with the last layer as transparency values

In [10]:
# create empty arrays for a_layer and rgba verion of sample
# create empty arrays for a_layer and sample_rgba
a_layer_out = a_layer = np.full((1,6,4), 1) #YES!! the trick is to make it a 1 layer 3D array
sample_rgba = np.empty((4,6,4), dtype=int)

In [11]:
# Identify locations of 4s in sample indicated by extract, and mark as 0 opacity in a_layer
for i in range(sample.shape[0]): #dimension
    for j in range(sample.shape[1]): # row
        for k in range(sample.shape[2]): #column
            if extract[0,j,k] ==4:
                a_layer_out[0,j,k] = 0 # I want zeros in every layer at that location if there is a 4 at that location in extract
            else:      
                pass

In [12]:
# vstack sample and opacity together to make rgba
sample_out = np.vstack((sample, a_layer_out))
sample_out

array([[[3, 2, 0, 0],
        [1, 3, 1, 4],
        [0, 4, 0, 1],
        [3, 1, 2, 1],
        [4, 2, 3, 0],
        [3, 2, 2, 1]],

       [[3, 3, 4, 2],
        [0, 1, 0, 1],
        [1, 3, 0, 1],
        [2, 0, 1, 3],
        [4, 3, 1, 4],
        [1, 2, 0, 4]],

       [[3, 4, 1, 1],
        [3, 2, 4, 4],
        [0, 4, 3, 1],
        [4, 0, 3, 0],
        [4, 2, 0, 1],
        [3, 2, 0, 1]],

       [[1, 0, 0, 1],
        [1, 1, 0, 0],
        [1, 0, 1, 1],
        [0, 1, 1, 1],
        [0, 1, 1, 0],
        [1, 1, 1, 0]]])